spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/notification
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: rabbit:5672

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
