server:
  port: 8083

spring:
  application:
    name: notification
  datasource:
    url: jdbc:postgresql://localhost:5432/notification
    password: postgres
    username: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  flyway:
    enabled: true
  zipkin:
    base-url: http://localhost:9411 # zipkin.base-url: http://localhost:9411 - default
  rabbitmq:
    addresses: localhost:5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

rabbit:
  exchanges:
    internal: internal.exchange
  queues:
      notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key
