spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://zipkin:9411

server:
  port: 8761

eureka:
  client:
    fetch-registry: false # true - only for clients
    register-with-eureka: false # true - only for clients
